# The imqcam-dagster-io-data PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: imqcam-dagster-io-data
  namespace: imqcam-dagster
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: imqcam-dagster-io-data
    namespace: imqcam-dagster
  nfs:
    server: sciserver-fs1
    path: /srv/vc_crypt/IMQCAM/dagster_filesystem_io
  persistentVolumeReclaimPolicy: Retain
---
# The imqcam-dagster-io-data PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: imqcam-dagster-io-data
  namespace: imqcam-dagster
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
