# The secret for holding the Girder connection info
apiVersion: v1
kind: Secret
metadata:
  name: girder-connection-info
  namespace: imqcam-dagster
type: Opaque
data:
  GIRDER_API_URL: base_64_encoded_girder_api_url
  GIRDER_API_KEY: base_64_encoded_girder_api_key
---
# The secret for holding the Globus Compute service account credentials
apiVersion: v1
kind: Secret
metadata:
  name: globus-compute-creds
  namespace: imqcam-dagster
type: Opaque
data:
  GLOBUS_COMPUTE_CLIENT_ID: base_64_encoded_globus_compute_client_id
  GLOBUS_COMPUTE_CLIENT_SECRET: base_64_encoded_globus_compute_client_secret
