# A pod to use for generally working with the different mounts and filesystems
apiVersion: v1
kind: Pod
metadata:
  name: utility-pod
  namespace: maggie-imqcam-dagster
spec:
  containers:
  - name: util-container
    image: containers.repo.sciserver.org/astropath/python_utils:latest
    command: [ "/bin/sleep", "infinity"]
    volumeMounts:
      - name: imqcam-dagster-io-data
        mountPath: /imqcam-dagster-io-data
  imagePullSecrets:
  - name: regcred
  volumes:
    - name: imqcam-dagster-io-data
      persistentVolumeClaim:
        claimName: imqcam-dagster-io-data
