# The imqcam-local-data PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: imqcam-local-data
  namespace: dagster
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: imqcam-local-data
    namespace: dagster
  hostPath:
    path: /tmp/imqcam_local_data
---
# The imqcam-local-data PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: imqcam-local-data
  namespace: dagster
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi