# The secret for holding the Girder connection info
apiVersion: v1
kind: Secret
metadata:
  name: girder-connection-info
  namespace: dagster
type: Opaque
data:
  GIRDER_API_URL: base_64_encoded_girder_api_url
  GIRDER_API_KEY: base_64_encoded_girder_api_key
